# ===============================
# SERVER CONFIG
# ===============================
server.port=5000

# ===============================
# DATABASE CONFIG (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/flysphere_db
spring.datasource.username=postgres
spring.datasource.password=Nttdata@123

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA CONFIG
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# JWT CONFIG
# ===============================
jwt.secret=FlySphereSecretKeyFlySphereSecretKey
jwt.expiration=86400000
